### ISSUE TITLE
Question about arguments

### ISSUE THREAD

**Issue by BlackalSaka** [enkomio/ManagedInjector#1]
Can I pass some arguments to .net assembly when I use ManagedInjector?

**Comment by enkomio** [comment]
Hi,

**Comment by enkomio** [comment]
Hi,
not currently, but I think it is a handy feature to have. I'll implement it (I'll keep this issue opened till the next release implementing this feature)

**Comment by enkomio** [comment]
Released version 2.0.0 implementing the requested feature.

For an example of usage see the example: https://github.com/enkomio/ManagedInjector/blob/master/Src/Examples/TestRunner/Program.cs#L138
